- name:  setup example production server
  hosts: example_production
  sudo:  true

  vars:
    common_path:      ../../common
    assets_path:      ../roles/example_production
    loop_assets_path: ../example_production

  roles:
    - ../roles/example_production

